// Code generated by reset-gen. DO NOT EDIT.
package model

func (r *BatchRequest) Reset() {
	if r == nil {
		return
	}
	r.CorrelationID = ""
	r.OriginalURL = ""
}

func (r *BatchResponse) Reset() {
	if r == nil {
		return
	}
	r.CorrelationID = ""
	r.ShortURL = ""
}

func (r *URL) Reset() {
	if r == nil {
		return
	}
	r.ShortURL = ""
	r.OriginalURL = ""
	r.UserID = ""
	r.IsDeleted = false
}
