package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

type StructInfo struct {
	Name   string
	Fields []*ast.Field
}

func main() {
	_ = filepath.Walk(".", walk)
}

func walk(path string, info os.FileInfo, err error) error {
	if err != nil {
		return nil
	}

	if info.IsDir() && strings.HasPrefix(info.Name(), ".") {
		return filepath.SkipDir
	}

	if !info.IsDir() && strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, "_test.go") {
		parseFile(path)
	}

	return nil
}

func parseFile(path string) {
	fset := token.NewFileSet()

	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return
	}

	var structs []StructInfo

	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}

		if !hasResetTag(gen) {
			continue
		}

		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}

			structs = append(structs, StructInfo{
				Name:   ts.Name.Name,
				Fields: st.Fields.List,
			})
		}
	}

	if len(structs) == 0 {
		return
	}

	generate(file.Name.Name, path, structs)
}

func hasResetTag(gen *ast.GenDecl) bool {
	if gen.Doc == nil {
		return false
	}

	for _, c := range gen.Doc.List {
		if strings.Contains(c.Text, "generate:reset") {
			return true
		}
	}
	return false
}

func generate(pkg, path string, structs []StructInfo) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by reset-gen. DO NOT EDIT.\n")
	buf.WriteString("package " + pkg + "\n\n")

	for _, s := range structs {
		buf.WriteString(fmt.Sprintf("func (r *%s) Reset() {\n", s.Name))
		buf.WriteString("if r == nil { return }\n")

		for _, f := range s.Fields {
			for _, name := range f.Names {
				buf.WriteString(buildResetStmt("r."+name.Name, f.Type))
			}
		}

		buf.WriteString("}\n\n")
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		out = buf.Bytes()
	}

	dir := filepath.Dir(path)
	_ = os.WriteFile(filepath.Join(dir, "reset.gen.go"), out, 0644)
}

func buildResetStmt(path string, t ast.Expr) string {
	switch v := t.(type) {

	case *ast.Ident:
		switch v.Name {
		case "string":
			return fmt.Sprintf("%s = \"\"\n", path)
		case "bool":
			return fmt.Sprintf("%s = false\n", path)
		default:
			return fmt.Sprintf("%s = 0\n", path)
		}

	case *ast.ArrayType:
		return fmt.Sprintf("%s = %s[:0]\n", path, path)

	case *ast.MapType:
		return fmt.Sprintf("clear(%s)\n", path)

	case *ast.StarExpr:
		return fmt.Sprintf(`if %s != nil {
	*%s = %s
}
`, path, path, zeroValue(v.X))

	default:
		return ""
	}
}

func zeroValue(t ast.Expr) string {
	switch v := t.(type) {
	case *ast.Ident:
		switch v.Name {
		case "string":
			return `""`
		case "bool":
			return "false"
		default:
			return "0"
		}
	}
	return "0"
}
