package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

type StructInfo struct {
	Name   string
	Fields []*ast.Field
}

var pkgStructs = make(map[string][]StructInfo)
var pkgNames = make(map[string]string)

func main() {
	_ = filepath.Walk(".", collectWalk)

	for dir, structs := range pkgStructs {
		if len(structs) == 0 {
			continue
		}
		pkgName := pkgNames[dir]
		if pkgName != "" {
			generate(dir, pkgName, structs)
		}
	}
}

func collectWalk(path string, info os.FileInfo, err error) error {
	if err != nil {
		return nil
	}

	if info.IsDir() {
		name := info.Name()
		if name != "." && name != ".." && strings.HasPrefix(name, ".") {
			return filepath.SkipDir
		}
		return nil
	}

	if strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, "_test.go") && !strings.HasSuffix(path, "reset.gen.go") {
		collectStructs(path)
	}

	return nil
}

func collectStructs(path string) {
	fset := token.NewFileSet()

	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return
	}

	dir := filepath.Dir(path)

	if _, exists := pkgNames[dir]; !exists {
		pkgNames[dir] = file.Name.Name
	}

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			if !hasGenerateTag(genDecl, typeSpec) {
				continue
			}

			pkgStructs[dir] = append(pkgStructs[dir], StructInfo{
				Name:   typeSpec.Name.Name,
				Fields: structType.Fields.List,
			})
		}
	}
}

func hasGenerateTag(gen *ast.GenDecl, spec *ast.TypeSpec) bool {
	check := func(cg *ast.CommentGroup) bool {
		if cg == nil {
			return false
		}
		for _, c := range cg.List {
			if strings.Contains(c.Text, "generate:reset") {
				return true
			}
		}
		return false
	}

	return check(gen.Doc) || check(spec.Doc) || check(spec.Comment)
}

func generate(dir, pkg string, structs []StructInfo) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by reset-gen. DO NOT EDIT.\n")
	buf.WriteString("package " + pkg + "\n\n")

	for _, s := range structs {
		buf.WriteString(fmt.Sprintf("func (r *%s) Reset() {\n", s.Name))
		buf.WriteString("if r == nil {\n    return\n}\n")

		for _, f := range s.Fields {
			for _, name := range f.Names {
				fieldPath := "r." + name.Name

				stmt := buildResetStmt(fieldPath, f.Type)
				if stmt == "" {
					continue
				}

				buf.WriteString(stmt)
			}
		}

		buf.WriteString("}\n\n")
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		out = buf.Bytes()
	}

	_ = os.WriteFile(filepath.Join(dir, "reset.gen.go"), out, 0644)
}

func buildResetStmt(path string, t ast.Expr) string {
	switch v := t.(type) {

	case *ast.Ident:
		switch v.Name {
		case "string":
			return fmt.Sprintf("%s = \"\"\n", path)
		case "bool":
			return fmt.Sprintf("%s = false\n", path)
		default:
			return fmt.Sprintf("%s = 0\n", path)
		}

	case *ast.ArrayType:
		return fmt.Sprintf("%s = %s[:0]\n", path, path)

	case *ast.MapType:
		return fmt.Sprintf("clear(%s)\n", path)

	case *ast.StarExpr:
		return buildPointerReset(path, v.X)

	case *ast.StructType:
		return fmt.Sprintf("if resetter, ok := interface{}(&%s).(interface{ Reset() }); ok { resetter.Reset() }\n", path)

	case *ast.SelectorExpr:
		return fmt.Sprintf("if resetter, ok := interface{}(&%s).(interface{ Reset() }); ok { resetter.Reset() }\n", path)

	default:
		return ""
	}
}

func buildPointerReset(path string, innerType ast.Expr) string {
	switch x := innerType.(type) {

	case *ast.Ident:
		switch x.Name {
		case "string":
			return fmt.Sprintf("if %s != nil {\n    *%s = \"\"\n}\n", path, path)
		case "bool":
			return fmt.Sprintf("if %s != nil {\n    *%s = false\n}\n", path, path)
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "complex64", "complex128",
			"byte", "rune":
			return fmt.Sprintf("if %s != nil {\n    *%s = 0\n}\n", path, path)
		default:
			return fmt.Sprintf("if %s != nil {\n   if resetter, ok := interface{}(%s).(interface{ Reset() }); ok { resetter.Reset() }\n}\n", path, path)
		}

	case *ast.ArrayType:
		return fmt.Sprintf("if %s != nil {\n    *%s = (*%s)[:0]\n}\n", path, path, path)

	case *ast.MapType:
		return fmt.Sprintf("if %s != nil {\n    clear(*%s)\n}\n", path, path)

	case *ast.StarExpr:
		return buildPointerReset(path, x.X)

	case *ast.SelectorExpr:
		return fmt.Sprintf("if %s != nil {\n    if resetter, ok := interface{}(%s).(interface{ Reset() }); ok { resetter.Reset() }\n}\n", path, path)

	default:
		return fmt.Sprintf("if %s != nil {\n    if resetter, ok := interface{}(%s).(interface{ Reset() }); ok { resetter.Reset() }\n}\n", path, path)
	}
}
